config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :recipes do
    member do
      post 'favorite'
      delete 'favorite', to: 'recipes#unfavorite', as: 'unfavorite'
      post 'share'
    end

    collection do
      get 'search'
    end
  end

  resources :favorites, only: [:index, :show, :create]
  resources :cuisines, only: [:show, :new, :create]
  resources :recipe_types, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
  validates :name, presence: true,
    uniqueness: { case_sensitive: false}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  belongs_to :user
  has_many :favorites, -> {order('recipe_id ASC')}, dependent: :destroy
  has_many :users, through: :favorites

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :title, :difficulty, :cook_time, :ingredients, :method,
    presence: { message: 'Você deve informar todos os dados da receita' }

  scope :recent, ->(n) { order(created_at: :desc).limit(n) }
  scope :most_favorited, -> (n) { joins(:favorites).distinct.limit(n) }

  # scope :favorited_by, -> (username) { joins(:favorites)
  #   .where(favorites: { user: User.where(name: username) }) }

end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
  validates :name, presence: true,
    uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :recipes
  has_many :favorite_recipes, through: :favorites, source: :recipe

  def favorited?(recipe)
    favorite_recipes.include? recipe
  end

  def author?(recipe)
    self.eql? recipe.user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_types,
    only: [:index, :show, :new, :edit, :create, :search]
  before_action :set_cuisines,
    only: [:index, :show, :new, :edit, :create, :search]

  private

  def set_cuisines
    @cuisines ||= Cuisine.all
  end

  def set_types
    @recipe_types ||= RecipeType.all
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def show
    @cuisine = Cuisine.find(params[:id])
    @recipes = Recipe.where(cuisine_id: params[:id])
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.create(cuisine_params)
    if @cuisine.save
      redirect_to @cuisine
    else
      flash.now[:error] = "Você deve informar o nome da cozinha"
      render 'new'
    end
  end

  private

  def cuisine_params
    params.require(:cuisine).permit(:name, :cuisine_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipe = Recipe.find(params[:id])
    @recipes = Recipe.all
    @favorites = Favorite.all
    @user = current_user

    @recipes.where(user_id: @user.id, recipe_id: @recipe.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.last(6)
    @favorited_recipes = Recipe.most_favorited(3)
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def show
    @recipe_type = RecipeType.find(params[:id])
    @recipes = Recipe.where(recipe_type_id: params[:id])
  end

  def new
     @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.create(recipe_type_params)
    if @recipe_type.save
      redirect_to @recipe_type
    else
      flash.now[:error] = "Você deve informar o nome do tipo de receita"
      render 'new'
    end
  end

  private

  def recipe_type_params
    params.require(:recipe_type).permit(:name, :recipe_type_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!,
    only: [:new, :create, :edit, :update, :destroy]
  before_action :set_recipe,
    only: [:show, :edit, :update, :destroy, :favorite, :unfavorite, :share]

  def index
    @recipes ||= Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    unless current_user.author?(@recipe)
      flash[:notice] = 'Você não tem permissão para editar essa receita'
      redirect_to root_path
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe
    else
      set_cuisines
      set_types
      render 'new'
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      set_cuisines
      set_types
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    flash[:notice] = 'Receita excluída'
    redirect_to root_path
  end

  def search
    @search_term = params[:term]
    search_term_query = "%#{@search_term}%"
    @recipes = Recipe.where("title LIKE ? OR ingredients LIKE ?",
      search_term_query, search_term_query)
      
    unless @recipes.any?
      flash[:error] = "Nenhuma receita encontrada com o termo #{@search_term}"
    end
  end

  def favorite
    @favorite = current_user.favorites.create(recipe: @recipe)
    if @favorite.valid?
      flash[:notice] = 'Receita adicionada aos favoritos'
      redirect_to recipe_path(@recipe)
    end
  end

  def unfavorite
    @favorite = Favorite.find_by(user: current_user, recipe: @recipe)
    @favorite.destroy
    flash[:notice] = 'Receita removida dos favoritos'
    redirect_to recipe_path(@recipe)
  end

  def share
    @email = params[:email]
    @message = params[:message]

    RecipesMailer.share(@email, @message, @recipe.id).deliver_now

    flash[:notice] = "Receita enviada para #{@email}"
    redirect_to @recipe
  end


  private

  def recipe_params
    params.require(:recipe).permit(:title, :difficulty, :cook_time,
      :ingredients, :method, :recipe_type_id, :cuisine_id, :user_id,
      :image, :star)
  end

  def set_recipe
    @recipe ||= Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/_form.html.erb
<%= form_for @cuisine do |f| %>
<div class="row">
  <div class="form-group col-md-2">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <br>
    <%= link_to "Voltar", root_path, class: "btn btn-default" %>
    <%= f.submit 'Enviar', class: "btn btn-primary" %><br>
  </div>

</div>

<% end %>
<br>
<%= flash[:error] %>
<br>
<%= render partial: 'shared/error', locals: {error: @cuisine} %>

app/views/cuisines/new.html.erb
<%= render 'form', cuisine: @cuisine %>

app/views/cuisines/show.html.erb
<section class="col-md-5">
  <h1><%= @cuisine.name %></h1>

  <% if @recipes.empty? %>
    <p>Nenhuma receita encontrada para este tipo de Cozinha</p>
  <% end %>

  <% @recipes.each do |recipe| %>
    <div class="col-md-12 col-xs-2">
      <%= render recipe %>
    </div>
  <% end %>
</section>

app/views/favorites/index.html.erb
<section class="col-md-4">
  <h2>Receitas Favoritas</h2>
  <% @recipes.each do |recipe| %>
    <div class="col-md-12 col-xs-2">
      <%= render recipe %>
    </div>
  <% end %>
</section>

app/views/favorites/show.html.erb
<h1><%= @recipe.name %></h1>
<br>
<%= link_to "Voltar", root_path, class: "btn btn-default" %>

app/views/home/index.html.erb
<%= render 'shared/recipes_section' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>My CookBook</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">

      <header class="col-md-12">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= render 'shared/header' %>
      </header>

      <aside class="col-md-2 col-xs-2 well">
        <%= render 'shared/aside' %>
      </aside>

      <main>
        <%= yield %>
      </main>

      <div class="row">
        <footer></footer>
      </div>

    </div>
  </body>
</html>

app/views/recipe_types/_form.html.erb
<%= form_for @recipe_type do |f| %>
  <div class="row">
    <div class="form-group col-md-2">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <br>
      <%= link_to "Voltar", root_path, class: "btn btn-default" %>
      <%= f.submit 'Enviar', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<br>
<%= flash[:error] %>
<br>
<%= render partial: 'shared/error', locals: {error: @recipe_type} %>

app/views/recipe_types/new.html.erb
<%= render 'form', recipe_type: @recipe_type %>

app/views/recipe_types/show.html.erb
<section class="col-md-5">
  <h1><%= @recipe_type.name %></h1>

  <% if @recipes.empty? %>
    <p>Nenhuma receita encontrada para este tipo de receitas</p>
  <% end %>

  <% @recipes.each do |recipe| %>
    <div class="col-md-12 col-xs-2">
      <%= render recipe %>
    </div>
  <% end %>
</section>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<div class="col-md-10">
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :title, 'Título' %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
     <%= f.label :star, 'Marcar como destaque' %> &nbsp;
     <%= f.check_box :star %>
    </div>
   </div>
  <div class="row">
    <div class="form-group col-md-2">
     <%= f.label :recipe_type_id %>
     <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name,
       { include_blank: false }, {class: "form-control"} %>
    </div>

   <div class="form-group col-md-2">
     <%= f.label :cuisine_id %>
     <%= f.collection_select :cuisine_id, @cuisines, :id, :name,
       { include_blank: false }, {class: "form-control"} %>
   </div>
  </div>
  <div class="row">
   <div class="form-group col-md-2">
     <%= f.label :difficulty %>
     <%= f.text_field :difficulty, class: "form-control" %>
   </div>

   <div class="form-group col-md-2">
     <%= f.label :cook_time %>
     <%= f.text_field :cook_time, class: "form-control" %>
   </div>
  </div>
  <div class="row">
   <div class="form-group col-md-4">
     <%= f.label :ingredients %>
     <%= f.text_area :ingredients, class: "form-control" %>
   </div>
  </div>
  <div class="row">
   <div class="form-group col-md-4">
     <%= f.label :method %>
     <%= f.text_area :method, class: "form-control" %>
   </div>
  </div>
  <div class="row">
   <div class="form-group col-md-4">
     <%= f.label :image, 'Insira uma foto da receita' %>
     <%= f.file_field :image, as: :file, class: "form-control" %>
   </div>
  </div>
  <%= link_to "Voltar", root_path, class: "btn btn-default" %>
  <%= f.submit 'Enviar', class: "btn btn-primary" %>
</div>
<% end %>

<%= render partial: 'shared/error', locals: {error: @recipe} %>

app/views/recipes/_recipe.html.erb
<h1><%= link_to(recipe.title, recipe) %><%= image_tag("star.png", size: "32x32", alt: "Destaque") if recipe.star? %></h1>
<div class="col-md-6">
  <%= link_to image_tag(recipe.image.url(:medium), class: "img-thumbnail"), recipe %>
</div>

<div class="col-md-6">
  <ul class="nav">
    <li>Tipo: <%= recipe.recipe_type.name %></li>
    <li>Cozinha: <%= recipe.cuisine.name %></li>
    <li>Dificuldade: <%= recipe.difficulty %></li>
    <li>Tempo de preparo: <%= recipe.cook_time %> minutos</li>
    <li><%= 'Favoritada ' + pluralize(recipe.favorites.count, 'vez', 'vezes') unless recipe.favorites.count < 1 %></li>
  </ul>
</div>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/favorites.html.erb
<section class="col-md-4">
  <h2>Receitas Favoritas</h2>
  <% @recipes.each do |recipe| %>
    <div class="col-md-12 col-xs-2">
      <%= render recipe %>
    </div>
  <% end %>
</section>

app/views/recipes/index.html.erb
<section class="col-md-5">
  <h2>Todas as Receitas</h2>

  <% @recipes.each do |recipe| %>
    <div class="col-md-12 col-xs-2">
      <%= render recipe %>
    </div>
  <% end %>
</section>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :recipe_type, 'Tipo da Receita' %>
    <%= f.text_field :recipe_type %>
  </div>
  <div>
    <%= f.label :cuisine_id, 'Cozinha' %>
    <%= f.collection_select :cuisine_id, @cuisines, :id, :name %>
  </div>
  <div>
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty %>
  </div>
  <div>
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time %>
  </div>
  <div>
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_area :ingredients %>
  </div>
  <div>
    <%= f.label :method, 'Como Preparar' %>
    <%= f.text_area :method %>
  </div>

  <%= f.submit 'Enviar'  %>
<% end %>

app/views/recipes/search.html.erb
<section class="col-md-5">
  <h2>Resultado da busca por <%= @search_term %></h2>
  <p><%= flash[:error] %></p>
  <% @recipes.each do |recipe| %>
    <div class="col-md-12 col-xs-2 recipes">
      <%= render recipe %>
    </div>
  <% end %>
</section>

app/views/recipes/show.html.erb
<div class="row">
  <div class="col-md-4">
    <h1><%= @recipe.title %><%= image_tag("star.png", size: "32x32", alt: "Destaque") if @recipe.star? %></h1>
    <%= image_tag @recipe.image.url(:medium), class: "img-thumbnail" %>
    <br>
    <br>
    <%= link_to "Voltar", root_path, class: "btn btn-default" %>
    <% if current_user && current_user.author?(@recipe) %>
      <%= link_to "Editar", edit_recipe_path(@recipe), class: "btn btn-primary" %>
      <%= link_to "Excluir Receita", recipe_path(@recipe), method: :delete,
        data: { confirm: 'Tem certeza?' }, class: "btn btn-danger" %>
    <% end %>
    <% if current_user && current_user.favorited?(@recipe) %>
      <%= link_to 'Remover dos favoritos', unfavorite_recipe_path(@recipe),
        method: :delete, class: "btn btn-default" %>
    <% elsif current_user && !current_user.favorited?(@recipe) %>
      <%= link_to 'Favoritar Receita', favorite_recipe_path(@recipe),
        method: :post, class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="col-md-5">
    <h3>Detalhes</h3>
    <p><strong>Prato: </strong><%= @recipe.recipe_type.name %></p>
    <p><strong>Cozinha de origem:</strong> <%= @recipe.cuisine.name %></p>
    <p><strong>Dificuldade: </strong><%= @recipe.difficulty %></p>
    <p><strong>Tempo de preparo: </strong><%= @recipe.cook_time %> minutos</p>
    <h3>Ingredientes</h3>
    <p><%= @recipe.ingredients %></p>
    <h3>Como Preparar</h3>
    <p><%= @recipe.method %></p>
    <br>
    <p><strong>Autor: </strong><%= @recipe.user.name %></p>

    <h3>Compartilhe essa receita com um amigo :)</h3>

    <%= form_tag share_recipe_path method: :post do %>
      <div class="row">
        <div class="form-group col-md-12">
          <%= label_tag :email, 'Email' %>
          <%= text_field_tag :email, nil, class: "form-control" %>
          <%= label_tag :message, 'Mensagem' %>
          <%= text_area_tag :message, nil, class: "form-control" %>
          <br>
          <%= submit_tag 'Enviar', class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_aside.html.erb
<h2>Tipo</h2>
<% @recipe_types.each do |recipe_type| %>
  <li class="nav"><%= link_to recipe_type.name, recipe_type_path(recipe_type.id)%></li>
<% end %>

<h2>Cozinha</h2>
<% @cuisines.each do |cuisine| %>
  <li class="nav"><%= link_to cuisine.name, cuisine_path(cuisine.id)%></li>
<% end %>

<hr>

<span><%= link_to 'Ver todas as receitas', recipes_path %></span>

app/views/shared/_error.html.erb
<% if error.errors.any? %>
<ul>
  <% error.errors.full_messages.each do |msg| %>
    <li class="nav"><%= msg %></li>
  <% end %>
</ul>
<% end %>

app/views/shared/_favorite_recipes_section.html.erb
<section class="col-md-4">
  <h2>Favoritas dos Usuários</h2>
  <!-- <% @recipes.each do |recipe| %>
    <div class="col-md-12">
      <h1><%= link_to recipe.title, recipe %></h1>
      <ul>
        <li>Tipo: <%= recipe.recipe_type.name %></li>
        <li>Cozinha: <%= recipe.cuisine.name %></li>
        <li>Dificuldade: <%= recipe.difficulty %></li>
        <li>Tempo de preparo: <%= recipe.cook_time %> minutos</li>
      </ul>
    </div>
  <% end %> -->
</section>

app/views/shared/_header.html.erb
<h1>My CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>
<div class="row">
  <nav class="navbar navbar-default">
    <%= form_tag(search_recipes_path, method: :get, class: "navbar-form navbar-left") do %>
      <div class="form-group">
        <%= text_field_tag(:term, nil, class: "form-control", id: "search", placeholder: "ex.: Feijoada") %>
        <%= submit_tag("Buscar", class: "btn btn-default") %>
      </div>
    <% end %>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item"><%= link_to 'Início', root_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Enviar uma receita', new_recipe_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Cadastrar uma cozinha', new_cuisine_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Cadastrar um tipo de receita', new_recipe_type_path, class: "nav-link" %></li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Bem vindo #{current_user.email}", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Entrar', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_recipes_section.html.erb
<section class="col-md-5 recent">
  <h2>Últimas Receitas</h2>

  <% @recipes.each do |recipe| %>
    <div class="col-md-12 col-xs-2">
      <%= render recipe %>
    </div>
  <% end %>
</section>

<section class="col-md-5 favorites">
  <h2>Favoritas dos usuários</h2>

  <% @favorited_recipes.each do |recipe| %>
    <div class="col-md-12 col-xs-2 favorites">
      <%= render recipe %>
    </div>
  <% end %>
</section>